### ISSUE TITLE
METexpress documentation needs to emphasize that database is separate

### ISSUE THREAD

**Issue by mollybsmith-noaa** [dtcenter/METexpress#13]
## Describe the Task ##
We talk about this in the weeds of the documentation, but we need to mention *in the introduction* that an existing METviewer database needs to be in place for METexpress to work. We got an email today from a user who was confused about this.

### Time Estimate ###
30 minutes.

### Relevant Deadlines ###
*NONE*

### Funding Source ###
*NONE*

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **development**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **development**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by mollybsmith-noaa** [comment]
I stressed even more in the introduction that there needs to be a pre-existing database before users can run METexpress.
