### ISSUE TITLE
Update link to METviewer documentation

### ISSUE THREAD

**Issue by mollybsmith-noaa** [dtcenter/METexpress#14]
*Replace italics below with details for this issue.*

## Describe the Task ##
The METexpress documentation (https://dtcenter.github.io/METexpress/development/Users_Guide/installation.html) still links to the old METviewer documentation page. The up-to-date link should be https://dtcenter.github.io/METviewer/latest/Users_Guide/installation.html.

### Time Estimate ###
30 minutes.

### Relevant Deadlines ###
NONE.

### Funding Source ###
NONE.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **development**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **development**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by mollybsmith-noaa** [comment]
I updated this link, but it should be updated again when METdbload has documentation that can be linked to.
