### ISSUE TITLE
Implement METcalcpy as the statistical package in METexpress

### ISSUE THREAD

**Issue by mollybsmith-noaa** [dtcenter/METexpress#17]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
METexpress should use the METcalcpy package to perform calculations, to ensure that it produces the same results as METviewer.

### Time Estimate ###
3-5 days

### Sub-Issues ###
- [ ] Add METcalcpy repo as a sub-module in METexpress.
- [ ] Utilize METcalcpy code for calculations.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **development**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **development**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by mollybsmith-noaa** [comment]
@bonnystrong @ksearight As of now I think there are two obstacles we'll need to overcome to make this work:

1. METexpress updates are released at a much greater frequency than METcalcpy updates, so if we need to change something in METexpress that also requires a change in METcalcpy, we'll either have to wait months for a METcalcpy update to be released, or we'll have to maintain our own branch of METcalcpy that we use for app builds (not best practice).
2. METcalcpy is tailored to how METviewer produces plots, but there are a few deliberate differences in our methodology. For example, METexpress excludes duplicate data while METviewer does not, and METexpress matches on both time and level while I believe METviewer just matches on time.

**Comment by mollybsmith-noaa** [comment]
Everything in METexpress is now using METcalcpy except for ensemble and MODE statistics. The former will be trivial to add, the latter not so much. The matching algorithm also needs to be updated to use the new data structures, but that shouldn't be too big a deal.

**Comment by mollybsmith-noaa** [comment]
This work has been largely done and I am creating a preliminary pull request. There are a few sub-tasks for future work, but I will create new, separate issues for those.
