### ISSUE TITLE
Add two database users and configure metexpress app user and metexpress metadata user to use them 

### ISSUE THREAD

**Issue by randytpierce** [dtcenter/METexpress#21]
We need two new database users, suggest "metexpress" (readonly) and "metadata"(read/write)
so that the operations performed by metexpress apps and metexpress metadata creation can be tracked
independently from the met_admin user.

## Describe the Enhancement ##
1) Add the two new users to the database
2) modify the my.cnf for metexpress
3) modify the settings files for the metexpress apps
### Time Estimate ###
1 day
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
randy pierce
ian McGinnis
### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **development**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **development**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by randytpierce** [comment]
We discovered that this has already been accomplished but wanted to document the current state of the users for future reference. Passwords and hostnames are faked for security.

###  metexpress and admin users exist which are used by metexpress
  There are also mv-admin and mvuser users. They’re used by metviewer.


### METviewer.  From metviewer mvservlet.properties 
 ```
  metviewer…
  db.host=metviewer...
  db.user=mvuser
  db.password=secret-fake-news
  db.managementSystem=aurora
```
### METexpress metadata user. From metexpress my.cnf
```
  metexpress .../.my.cnf
  [client]
  user = admin
  password = secret-fake-news
  host = metviewer...
  [mysql]
  database = mats_metadata
```
###  metexpress - from one of the settings files
Apps users are defined in settings/[app]/settings.json and all apps are the same
```
   
   "private": {
      "databases": [
        {
          "role": "sums_data",
          "status": "active",
          "host": "metviewer…”
          "user": "metexpress",
          "password": "secret-fake-news",
          "database": "mats_metadata",
          "connectionLimit": 4
        }
      ],
  ```
